version: '3.8'
services:
  db:
    image: postgres:15
    container_name: postgres-complaints
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: complaints
    ports:
      - '5433:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d complaints"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  db-data:
